services:
  server:
    build:
      context: ./server
    environment:
      - CORS_ORIGIN=${DOMAIN}
      - MONGO_HOST=mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: npm run dev

  client:
    build:
      context: ./client
      args:
        - API_URL=${DOMAIN}:5000/api
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/dist
      - /app/src/environments
    ports:
      - "4200:4200"
    command: npm run start

  mongo:
    image: mongo:5.0.2
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db
