services:
  server:
    build:
      context: ./server
    environment:
      - CORS_ORIGIN=${DOMAIN}
    expose:
      - 5000
  client:
    build:
      context: ./client
      args:
        - API_URL=${API_URL}
    expose:
      - 4000

  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
