services:
  server:
    build:
      context: ./server
    environment:
      - CORS_ORIGIN=${DOMAIN}
      - MONGO_HOST=mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - 5000

  client:
    build:
      context: ./client
      args:
        - API_URL=${DOMAIN}/api
    expose:
      - 4000

  mongo:
    image: mongo:5.0.2
    container_name: mongo_container
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data.prod:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
