map $http_accept_language $lang {
    default es;
    ~*^en en;
    ~*^es es;
}

server {
    listen       80;
    server_name  localhost;

    location /api {
        proxy_pass http://server:5000/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = / {
        return 302 /$lang/;
    }

    location ~ ^/(es|en)/ {
        proxy_pass http://client:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_intercept_errors on;
        error_page 404 =200 /$1/index.html;
    }

    location ~ \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico|webmanifest)$ {
        proxy_pass http://client:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
