name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test Server
        run: npm test

  deploy:
    name: Deploy to Server
    needs: test
    if: |
      always() &&
      (github.event_name == 'push' && github.ref == 'refs/heads/main') &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create Production .env
        run: |
          cat << EOF > .env
          ${{ secrets.PROD_ENV_FILE }}
          EOF

      - name: Docker Compose Deploy
        run: |
          docker compose build
          docker compose -f docker-compose.prod.yml up -d
          docker image prune -f
